<?php
// desserts_data.php
// Array of dessert dishes with detailed info
return [
    // --- Indian Desserts (60%) ---
    [
        'name' => 'Gulab Jamun',
        'image' => 'https://images.slurrp.com/prod/articles/1m5e86yy5vl.webp',
        'description' => 'Soft, deep-fried milk balls soaked in rose-flavored sugar syrup.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Uttar Pradesh',
        'city' => 'Kanpur',
    ],
    [
        'name' => 'Rasgulla',
        'image' => 'https://i.pinimg.com/originals/98/3a/e8/983ae84fe28972ce2016da5dbb27f7c9.jpg',
        'description' => 'Spongy cottage cheese balls soaked in light sugar syrup.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Boiled',
        'state' => 'West Bengal',
        'city' => 'Kolkata',
    ],
    [
        'name' => 'Jalebi',
        'image' => 'https://th.bing.com/th/id/R.ebf00c0df8d033eb4559c63ea9ef9e81?rik=VvS6gp3VYXWDLQ&riu=http%3a%2f%2frecipes.timesofindia.com%2fphoto%2f53099699.cms&ehk=6a4KDqN4ldnVGme4C5ujN3oarGD%2boXp27I8zyCyux%2b4%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Crispy, spiral-shaped sweet soaked in saffron sugar syrup.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Uttar Pradesh',
        'city' => 'Varanasi',
    ],
    [
        'name' => 'Kaju Katli',
        'image' => 'https://recipes.timesofindia.com/thumb/55048826.cms?imgsize=392932&width=800&height=800',
        'description' => 'Diamond-shaped cashew fudge, smooth and rich in flavor.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'Maharashtra',
        'city' => 'Mumbai',
    ],
    [
        'name' => 'Rasmalai',
        'image' => 'https://rachnas-kitchen.com/wp-content/uploads/2017/09/rasmalai-1-gpo-700-1050.jpg',
        'description' => 'Soft cheese patties soaked in sweet, saffron-flavored milk.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Boiled',
        'state' => 'West Bengal',
        'city' => 'Kolkata',
    ],
    [
        'name' => 'Mysore Pak',
        'image' => 'https://images.herzindagi.info/image/2019/Apr/mysore-pak-image.jpg',
        'description' => 'Rich, ghee-laden sweet made from gram flour and sugar.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'Karnataka',
        'city' => 'Mysore',
    ],
    [
        'name' => 'Sandesh',
        'image' => 'https://www.mapsofindia.com/ci-moi-images/my-india/Mango-Sandesh.jpg',
        'description' => 'Delicate Bengali sweet made from fresh paneer and sugar.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'West Bengal',
        'city' => 'Kolkata',
    ],
    [
        'name' => 'Peda',
        'image' => 'https://th.bing.com/th/id/R.936043430b01fa2babdb66b7c8a70966?rik=u662K3vFjUHiZA&riu=http%3a%2f%2fwww.vegrecipesofindia.com%2fwp-content%2fuploads%2f2017%2f10%2fpeda-recipe18.jpg&ehk=XYZY7sZV%2f4Wk%2fLi9JdSvQ50wOPPR9vU1iL9FTbdigSs%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Soft, thick, and sweet milk fudge flavored with cardamom.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Cooked',
        'state' => 'Uttar Pradesh',
        'city' => 'Mathura',
    ],
    [
        'name' => 'Barfi',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.IaxY5gPsolEtVcbhjfzYoAHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Dense, milk-based sweet, often flavored with nuts or coconut.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Cooked',
        'state' => 'Punjab',
        'city' => 'Amritsar',
    ],
    [
        'name' => 'Ladoo',
        'image' => 'https://im.indiatimes.in/content/2022/Mar/ladoo1_621e33b0689da.jpg',
        'description' => 'Round, bite-sized sweets made from flour, ghee, and sugar.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Cooked',
        'state' => 'Maharashtra',
        'city' => 'Nagpur',
    ],
    // ... (Add 26 more Indian desserts here, following the same structure) ...
    // --- International Desserts (40%) ---
    [
        'name' => 'Chocolate Cake',
        'image' => 'https://i.pinimg.com/originals/ed/14/7c/ed147c3f95257010aa2b6b8f5ffc1a8e.jpg',
        'description' => 'Rich chocolate sponge layered with creamy chocolate frosting.',
        'cuisine_type' => 'American',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'California',
        'city' => 'Los Angeles',
    ],
    [
        'name' => 'Tiramisu',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.g6OCL5qbY-Nnp-jUe3qzeQHaE7?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Italian dessert with coffee-soaked ladyfingers and mascarpone.',
        'cuisine_type' => 'Italian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$$',
        'cooking_style' => 'Assembled',
        'state' => 'Veneto',
        'city' => 'Treviso',
    ],
    [
        'name' => 'Cheesecake',
        'image' => 'https://th.bing.com/th/id/R.634fa577892c3ff6717ddc8c97a396d9?rik=6pyiG1yVAsgFcA&riu=http%3a%2f%2fwww.taste.com.au%2fimages%2frecipes%2fagt%2f2008%2f05%2f19621.jpg&ehk=5yT6egtaJbt%2bAOKsKjm5tJmh3i%2b0OcKZcPvEIHuQy%2fQ%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Creamy cheese filling on a crumbly biscuit base, often topped with fruit.',
        'cuisine_type' => 'American',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$$',
        'cooking_style' => 'Baked',
        'state' => 'New York',
        'city' => 'New York City',
    ],
    [
        'name' => 'Baklava',
        'image' => 'https://www.mygreekdish.com/wp-content/uploads/2013/05/Traditional-Greek-Baklava-recipe-with-honey-and-walnuts-1-scaled.jpeg',
        'description' => 'Layers of filo pastry, nuts, and honey syrup.',
        'cuisine_type' => 'Turkish',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'Istanbul',
        'city' => 'Istanbul',
    ],
    [
        'name' => 'Pavlova',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.cozNkSgk9lI9H3LMfZQJOgHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Crisp meringue base topped with whipped cream and fruit.',
        'cuisine_type' => 'Australian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'New South Wales',
        'city' => 'Sydney',
    ],
    // ... (Add 17 more international desserts here, following the same structure) ...
    // --- More Indian Desserts ---
    [
        'name' => 'Shrikhand',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.-Dy8t8zgLmUr1YsJ-EvXFQHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Sweetened strained yogurt flavored with saffron and cardamom.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Chilled',
        'state' => 'Maharashtra',
        'city' => 'Pune',
    ],
    [
        'name' => 'Phirni',
        'image' => 'https://th.bing.com/th/id/R.b0236bb489f9d5de10e69ffdfef9e34f?rik=%2bKV5C567faQxFA&riu=http%3a%2f%2f1.bp.blogspot.com%2f-lUqFw5_eQ98%2fUekP6Ki74DI%2fAAAAAAAACUQ%2f1c5AraQL-Is%2fs1600%2fPhirni%2bor%2ba%2bIndian%2bsweet%2brice%2bdessert%2bset%2bin%2ba%2bearthern%2bpot.jpg&ehk=bzEfxZxuzbrvGso%2b8gZXVxSX08wXnA0biqcg%2bN0ELls%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Ground rice pudding flavored with cardamom and saffron.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Boiled',
        'state' => 'Punjab',
        'city' => 'Ludhiana',
    ],
    [
        'name' => 'Malpua',
        'image' => 'https://i2.wp.com/vegecravings.com/wp-content/uploads/2017/07/malpua-recipe-step-by-step-instructions-17.jpg?fit=1991%2C1944&ssl=1',
        'description' => 'Sweet pancakes soaked in sugar syrup, often served with rabri.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Odisha',
        'city' => 'Puri',
    ],
    [
        'name' => 'Kheer',
        'image' => 'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/06/kheer-recipe.jpg',
        'description' => 'Rice pudding cooked with milk, sugar, and cardamom.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Boiled',
        'state' => 'Uttar Pradesh',
        'city' => 'Lucknow',
    ],
    [
        'name' => 'Kulfi',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.iY51Nm9joxiEd9LxdPxb-QHaFe?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Traditional Indian ice cream made with thickened milk and nuts.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Frozen',
        'state' => 'Delhi',
        'city' => 'Delhi',
    ],
    [
        'name' => 'Rabri',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.zGb3wcwAAc4r6O0xQVkbtAAAAA?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Thickened sweetened milk with layers of cream, flavored with cardamom.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'Uttar Pradesh',
        'city' => 'Agra',
    ],
    [
        'name' => 'Basundi',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.c2kZxni0WzctnLdpoadBKQHaFj?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Sweetened condensed milk dessert flavored with cardamom and saffron.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'Gujarat',
        'city' => 'Surat',
    ],
    [
        'name' => 'Mohanthal',
        'image' => 'https://rakskitchen.net/wp-content/uploads/2022/09/mohanthal-720x720.jpg',
        'description' => 'Gram flour fudge flavored with cardamom and garnished with nuts.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'Gujarat',
        'city' => 'Bhavnagar',
    ],
    [
        'name' => 'Imarti',
        'image' => 'https://images.herzindagi.info/image/2022/Nov/jaggery-imarti.jpg',
        'description' => 'Flower-shaped deep-fried sweet made from urad dal batter, soaked in syrup.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Madhya Pradesh',
        'city' => 'Indore',
    ],
    [
        'name' => 'Chhena Poda',
        'image' => 'https://tse4.mm.bing.net/th/id/OIP.yrHlU5NDxF8tXL0JxyiaqwHaGc?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Baked cheese dessert from Odisha, caramelized on the outside.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'Odisha',
        'city' => 'Bhubaneswar',
    ],
    [
        'name' => 'Kesari Bath',
        'image' => 'https://static.toiimg.com/thumb/86602312.cms?imgsize=64212&width=509&height=340',
        'description' => 'Semolina pudding flavored with saffron and ghee.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Cooked',
        'state' => 'Karnataka',
        'city' => 'Bangalore',
    ],
    [
        'name' => 'Patishapta',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.o_tOduQ9s9QZklyecHJyRwHaD4?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Bengali crepes filled with coconut and jaggery.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'West Bengal',
        'city' => 'Kolkata',
    ],
    [
        'name' => 'Double Ka Meetha',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.h5Azz6kDFK_DR0ZG4IxVKQHaEg?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Hyderabadi bread pudding made with fried bread, milk, and sugar.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'Telangana',
        'city' => 'Hyderabad',
    ],
    [
        'name' => 'Puran Poli',
        'image' => 'https://cookwithrenu.com/wp-content/uploads/2020/09/Puran-Poli_Featured-Image.jpg',
        'description' => 'Sweet flatbread stuffed with jaggery and lentils.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Griddled',
        'state' => 'Maharashtra',
        'city' => 'Pune',
    ],
    [
        'name' => 'Sutarfeni',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.ovd6eLsmfSeW4fEOq-fV8gHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Fine, thread-like sweet made from flour and sugar, flavored with cardamom.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'Gujarat',
        'city' => 'Ahmedabad',
    ],
    [
        'name' => 'Balushahi',
        'image' => 'https://www.ruchiskitchen.com/wp-content/uploads/2017/10/balushahi-recipe-5-682x1024.jpg',
        'description' => 'Deep-fried doughnut-like sweet soaked in sugar syrup.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Bihar',
        'city' => 'Patna',
    ],
    [
        'name' => 'Kharwas',
        'image' => 'https://i.ytimg.com/vi/OiAMFt70vWE/maxresdefault.jpg',
        'description' => 'Steamed milk pudding made from colostrum milk, flavored with cardamom.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Steamed',
        'state' => 'Maharashtra',
        'city' => 'Kolhapur',
    ],
    [
        'name' => 'Ghevar',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.rmKXAPjjHInMwOsLW2d_zwHaLO?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Disc-shaped sweet made from flour and soaked in sugar syrup, topped with rabri.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'Rajasthan',
        'city' => 'Jaipur',
    ],
    [
        'name' => 'Payasam',
        'image' => 'https://www.indianhealthyrecipes.com/wp-content/uploads/2014/08/semiya-payasam.jpg',
        'description' => 'South Indian rice pudding made with coconut milk, jaggery, and cardamom.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Boiled',
        'state' => 'Kerala',
        'city' => 'Thiruvananthapuram',
    ],
    [
        'name' => 'Misti Doi',
        'image' => 'https://th.bing.com/th/id/R.371cb05de5984d1cc433ca2d163bb26d?rik=56wBldQngOYC2A&riu=http%3a%2f%2fbengalicuisine.net%2fwp-content%2fuploads%2f2009%2f08%2fMishti-Doi-2.JPG&ehk=AAzbinHoCIgNaA8m3bNDO4%2b0Uxsz4Wm3jV2HefHs5Cg%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Sweetened yogurt dessert from Bengal, thick and creamy.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fermented',
        'state' => 'West Bengal',
        'city' => 'Kolkata',
    ],
    [
        'name' => 'Sheer Khurma',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.hm4ujcqs0et_AzFz6qGEFQHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Vermicelli pudding with milk, dates, and nuts, popular during Eid.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Boiled',
        'state' => 'Hyderabad',
        'city' => 'Hyderabad',
    ],
    [
        'name' => 'Chikki',
        'image' => 'https://tse4.mm.bing.net/th/id/OIP.WhixCFJJGRJh1ZCMNvlAzQHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Brittle sweet made from jaggery and peanuts or sesame seeds.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Cooked',
        'state' => 'Maharashtra',
        'city' => 'Lonavala',
    ],
    [
        'name' => 'Kozhukattai',
        'image' => 'https://www.vegrecipesofindia.com/wp-content/uploads/2018/09/kozhukattai-recipe-1a.jpg',
        'description' => 'Steamed rice flour dumplings filled with coconut and jaggery.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Steamed',
        'state' => 'Tamil Nadu',
        'city' => 'Chennai',
    ],
    [
        'name' => 'Pathishapta',
        'image' => 'https://images.slurrp.com/prod/recipe_images/transcribe/ankush/Patishapta.webp',
        'description' => 'Bengali crepes filled with coconut and jaggery.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'West Bengal',
        'city' => 'Kolkata',
    ],
    [
        'name' => 'Unniyappam',
        'image' => 'https://i.pinimg.com/originals/f7/64/cc/f764ccf3d80c06304946ee17ac16d096.jpg',
        'description' => 'Small round fritters made from rice, banana, and jaggery.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Kerala',
        'city' => 'Alappuzha',
    ],
    [
        'name' => 'Pinni',
        'image' => 'https://images.indianexpress.com/2019/11/Pinni_759.jpg',
        'description' => 'Punjabi winter sweet made from wheat flour, ghee, and nuts.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'Punjab',
        'city' => 'Amritsar',
    ],
    [
        'name' => 'Kharvas',
        'image' => 'https://static.vecteezy.com/system/resources/previews/016/286/242/non_2x/kharvas-or-cheek-chik-bari-pis-or-junnu-is-a-sweet-dairy-product-made-from-bovine-colostrum-free-photo.jpg',
        'description' => 'Steamed milk pudding made from colostrum milk, flavored with cardamom.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Steamed',
        'state' => 'Maharashtra',
        'city' => 'Kolhapur',
    ],
    [
        'name' => 'Kunda',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.FnJvOtuhkf28q8mCFbECsAHaGH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Caramelized milk sweet from Belgaum, Karnataka.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'Karnataka',
        'city' => 'Belgaum',
    ],
    [
        'name' => 'Pootharekulu',
        'image' => 'https://assets.zeezest.com/blogs/PROD_Pootharekulu%20Recipe%20How%20to%20Make%20this%20Sweet%20Delicacy%20at%20Home%20with%20Simple%20Ingredients%20(1)_1722352632348_thumb_1200.jpeg',
        'description' => 'Paper-thin sweet made from rice starch and filled with jaggery and ghee.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'Andhra Pradesh',
        'city' => 'Atreyapuram',
    ],
    [
        'name' => 'Sohan Halwa',
        'image' => 'https://sunhillpure.com/wp-content/uploads/2021/03/halwa3.jpg',
        'description' => 'Dense sweet made from wheat, ghee, and nuts, popular in North India.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'Uttar Pradesh',
        'city' => 'Lucknow',
    ],
    [
        'name' => 'Makhane ki Kheer',
        'image' => 'https://www.cookclickndevour.com/wp-content/uploads/2019/10/makhana-kheer-recipe.jpg',
        'description' => 'Puffed lotus seed pudding cooked with milk and sugar.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Boiled',
        'state' => 'Bihar',
        'city' => 'Patna',
    ],
    [
        'name' => 'Tilkut',
        'image' => 'https://images.slurrp.com/prod/articles/zkd53j2l2b.webp',
        'description' => 'Sesame seed brittle sweet, especially popular during Makar Sankranti.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Cooked',
        'state' => 'Bihar',
        'city' => 'Gaya',
    ],
    [
        'name' => 'Kharvas',
        'image' => 'https://static.vecteezy.com/system/resources/previews/016/286/242/non_2x/kharvas-or-cheek-chik-bari-pis-or-junnu-is-a-sweet-dairy-product-made-from-bovine-colostrum-free-photo.jpg',
        'description' => 'Steamed milk pudding made from colostrum milk, flavored with cardamom.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Steamed',
        'state' => 'Maharashtra',
        'city' => 'Kolhapur',
    ],
    [
        'name' => 'Kunda',
        'image' => 'https://img1.exportersindia.com/product_images/bc-full/dir_112/3348120/kunda-2111463.jpg',
        'description' => 'Caramelized milk sweet from Belgaum, Karnataka.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'Karnataka',
        'city' => 'Belgaum',
    ],
    [
        'name' => 'Pootharekulu',
        'image' => 'https://images.slurrp.com/prodrich_article/mpx634wg4pc.webp?impolicy=slurrp-20210601&width=880&height=500',
        'description' => 'Paper-thin sweet made from rice starch and filled with jaggery and ghee.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Cooked',
        'state' => 'Andhra Pradesh',
        'city' => 'Atreyapuram',
    ],
    
]; 