<?php
// drinks_data.php
// Array of drink items with detailed info
return [
    // --- Indian Drinks (60%) ---
    [
        'name' => 'Masala Chai',
        'image' => 'https://masalaandchai.com/wp-content/uploads/2021/07/Masala-Chai-Featured.jpg',
        'description' => 'Spiced Indian tea brewed with milk, sugar, and aromatic spices.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Tea',
        'flavor_profile' => 'Spicy, Sweet',
        'serving_temp' => 'Hot',
        'price_range' => '$',
        'state' => 'West Bengal',
        'city' => 'Kolkata',
    ],
    [
        'name' => 'Lassi',
        'image' => 'https://www.indianveggiedelight.com/wp-content/uploads/2023/01/sweet-lassi-recipe-1-1152x1536.jpg',
        'description' => 'Traditional yogurt-based drink, sweet or salty, served chilled.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Yogurt Drink',
        'flavor_profile' => 'Sweet, Tangy',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Punjab',
        'city' => 'Amritsar',
    ],
    [
        'name' => 'Jaljeera',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.6F3hh4JdNZ7CrxjuyUZZlAHaEK?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Refreshing cumin-flavored drink with tangy spices and mint.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Spiced Drink',
        'flavor_profile' => 'Tangy, Spicy',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Uttar Pradesh',
        'city' => 'Lucknow',
    ],
    [
        'name' => 'Aam Panna',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.hxhXRKaDMJXJ3DBPdDb8QwHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Cooling summer drink made from raw mangoes, mint, and spices.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Fruit Drink',
        'flavor_profile' => 'Tangy, Sweet',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Maharashtra',
        'city' => 'Mumbai',
    ],
    [
        'name' => 'Thandai',
        'image' => 'https://aromaticessence.co/wp-content/uploads/2022/03/thandai_1.jpg',
        'description' => 'Festive drink with milk, nuts, spices, and rose petals, served chilled.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Milk Drink',
        'flavor_profile' => 'Nutty, Spicy',
        'serving_temp' => 'Cold',
        'price_range' => '$$',
        'state' => 'Uttar Pradesh',
        'city' => 'Varanasi',
    ],
    [
        'name' => 'Filter Coffee',
        'image' => 'https://static.vecteezy.com/system/resources/previews/013/754/273/large_2x/south-indian-filter-coffee-served-in-a-traditional-brass-or-stainless-steel-cup-free-photo.jpg',
        'description' => 'South Indian strong coffee brewed with milk and sugar.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Coffee',
        'flavor_profile' => 'Strong, Sweet',
        'serving_temp' => 'Hot',
        'price_range' => '$',
        'state' => 'Tamil Nadu',
        'city' => 'Chennai',
    ],
    [
        'name' => 'Sugarcane Juice',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.QTCudTwk4Mz71L0KqtlHzAHaEK?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Freshly pressed juice from sugarcane, served with lemon and ginger.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Juice',
        'flavor_profile' => 'Sweet, Refreshing',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Maharashtra',
        'city' => 'Pune',
    ],
    [
        'name' => 'Sol Kadhi',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.hpAZytWJd5MtYHpfeUSCIQHaDS?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Konkani drink made from kokum and coconut milk, cooling and tangy.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Coconut Drink',
        'flavor_profile' => 'Tangy, Creamy',
        'serving_temp' => 'Cold',
        'price_range' => '$$',
        'state' => 'Goa',
        'city' => 'Panaji',
    ],
    [
        'name' => 'Badam Milk',
        'image' => 'https://www.thespruceeats.com/thmb/aXBZePco3iakbaZyPC4LamgwVEI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/SES-badam-milk-with-cardamom-1957418-f94ebb8b20b9421ba4688cd7570d36e0.jpg',
        'description' => 'Sweetened milk flavored with almonds, saffron, and cardamom.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Milk Drink',
        'flavor_profile' => 'Nutty, Sweet',
        'serving_temp' => 'Hot or Cold',
        'price_range' => '$$',
        'state' => 'Telangana',
        'city' => 'Hyderabad',
    ],
    [
        'name' => 'Neer Mor',
        'image' => 'https://www.sailusfood.com/wp-content/uploads/2016/04/neer-mor.jpg',
        'description' => 'Spiced buttermilk with curry leaves, ginger, and green chili.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Buttermilk',
        'flavor_profile' => 'Spicy, Tangy',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Tamil Nadu',
        'city' => 'Madurai',
    ],
    // ... (Add 26 more Indian drinks here, following the same structure) ...
    // --- International Drinks (40%) ---
    [
        'name' => 'Vodka Martini',
        'image' => 'https://www.liquor.com/thmb/FtK86O9W4_pRq1Y3gc1iJerTGP8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/vodka-martini-1500x1500-hero-080af5bb8ff04851a9c0ecf77a88a818.jpg',
        'description' => 'Classic cocktail with vodka and dry vermouth, garnished with an olive.',
        'cuisine_type' => 'International',
        'drink_type' => 'Alcoholic',
        'category' => 'Cocktail',
        'flavor_profile' => 'Strong, Dry',
        'serving_temp' => 'Cold',
        'price_range' => '$$$',
        'state' => 'California',
        'city' => 'Los Angeles',
    ],
    [
        'name' => 'Red Wine',
        'image' => 'https://www.homenaturalcures.com/wp-content/uploads/red-wine.jpg',
        'description' => 'Rich and flavorful, made from dark grape varieties.',
        'cuisine_type' => 'International',
        'drink_type' => 'Alcoholic',
        'category' => 'Wine',
        'flavor_profile' => 'Fruity, Dry',
        'serving_temp' => 'Room Temp',
        'price_range' => '$$$',
        'state' => 'Bordeaux',
        'city' => 'Bordeaux',
    ],
    [
        'name' => 'White Wine',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.5yGE8uOLJ_7bl4ksCh5WYAHaFs?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Crisp and refreshing, made from green or yellow grapes.',
        'cuisine_type' => 'International',
        'drink_type' => 'Alcoholic',
        'category' => 'Wine',
        'flavor_profile' => 'Crisp, Light',
        'serving_temp' => 'Cold',
        'price_range' => '$$$',
        'state' => 'California',
        'city' => 'Napa Valley',
    ],
    [
        'name' => 'Coca-Cola',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.8Mrayjrp4QfG6Vf4S6T-KQHaFj?r=0&w=1024&h=768&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Classic carbonated soft drink, sweet and fizzy.',
        'cuisine_type' => 'International',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Soft Drink',
        'flavor_profile' => 'Sweet, Fizzy',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Georgia',
        'city' => 'Atlanta',
    ],
    [
        'name' => 'Orange Juice',
        'image' => 'https://wallpaperaccess.com/full/2185825.jpg',
        'description' => 'Freshly squeezed juice from ripe oranges.',
        'cuisine_type' => 'International',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Juice',
        'flavor_profile' => 'Citrus, Sweet',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Florida',
        'city' => 'Orlando',
    ],
    // ... (Add 17 more international drinks here, following the same structure) ...
    // --- More Indian Drinks ---
    [
        'name' => 'Kokum Sherbet',
        'image' => 'https://thumbs.dreamstime.com/b/kokum-sharbat-juice-sherbet-summer-coolant-drink-made-up-garcinia-indica-kokum-sharbat-juice-sherbet-summer-coolant-116336448.jpg',
        'description' => 'Sweet and tangy drink made from kokum fruit, popular in the west coast of India.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Fruit Drink',
        'flavor_profile' => 'Tangy, Sweet',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Maharashtra',
        'city' => 'Ratnagiri',
    ],
    [
        'name' => 'Sattu Sharbat',
        'image' => 'https://tse4.mm.bing.net/th/id/OIP.J0Xp3qGApTLsM20jL752iwHaJ4?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Nutritious summer drink made from roasted gram flour, lemon, and spices.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Grain Drink',
        'flavor_profile' => 'Earthy, Tangy',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Bihar',
        'city' => 'Patna',
    ],
    [
        'name' => 'Rose Milk',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.ntdbQLSWZaH6pcZdLmo0ogHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Chilled milk flavored with rose syrup, a favorite in South India.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Milk Drink',
        'flavor_profile' => 'Floral, Sweet',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Tamil Nadu',
        'city' => 'Chennai',
    ],
    [
        'name' => 'Chaas',
        'image' => 'https://www.spiceupthecurry.com/wp-content/uploads/2020/07/masala-chaas-1-1024x1536.jpg',
        'description' => 'Spiced buttermilk, a cooling drink for hot Indian summers.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Buttermilk',
        'flavor_profile' => 'Tangy, Spicy',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Gujarat',
        'city' => 'Ahmedabad',
    ],
    [
        'name' => 'Nimbu Pani',
        'image' => 'https://www.cookwithmanali.com/wp-content/uploads/2022/06/Nimbu-Paani.jpg',
        'description' => 'Indian-style lemonade with lemon, sugar, salt, and spices.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Lemonade',
        'flavor_profile' => 'Citrus, Sweet, Salty',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Delhi',
        'city' => 'Delhi',
    ],
    [
        'name' => 'Falooda',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.KpEqTT--WXTShcugKLaEAgAAAA?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Dessert drink with vermicelli, basil seeds, rose syrup, and milk.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Dessert Drink',
        'flavor_profile' => 'Sweet, Floral',
        'serving_temp' => 'Cold',
        'price_range' => '$$',
        'state' => 'Maharashtra',
        'city' => 'Mumbai',
    ],
    [
        'name' => 'Kesar Doodh',
        'image' => 'https://th.bing.com/th/id/R.1179c086b8f42501215c377ea9f11d15?rik=QqiNkk4%2bHq7F%2bw&riu=http%3a%2f%2fwww.jainrasoi.com%2fmg%2fwp-content%2fuploads%2f2012%2f09%2fkesar-doodh.jpg&ehk=9Et5fPi30kR89a9agQzPRD6Mci2%2brmedl5veGLKvYy4%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Milk flavored with saffron and cardamom, served hot or cold.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Milk Drink',
        'flavor_profile' => 'Sweet, Aromatic',
        'serving_temp' => 'Hot or Cold',
        'price_range' => '$$',
        'state' => 'Rajasthan',
        'city' => 'Jaipur',
    ],
    [
        'name' => 'Tadi (Palm Wine)',
        'image' => 'https://tse1.explicit.bing.net/th/id/OIP.eXj20bdgzQFD58EitB4-MwHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Mildly alcoholic drink tapped from palm trees, popular in rural India.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Alcoholic',
        'category' => 'Fermented Drink',
        'flavor_profile' => 'Fruity, Mild',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Andhra Pradesh',
        'city' => 'Vijayawada',
    ],
    [
        'name' => 'Feni',
        'image' => 'https://cdn.thegoavilla.com/static/img/articles/feni-in-goa.jpg',
        'description' => 'Goan spirit distilled from cashew apples or coconut sap.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Alcoholic',
        'category' => 'Spirit',
        'flavor_profile' => 'Fruity, Strong',
        'serving_temp' => 'Room Temp',
        'price_range' => '$$',
        'state' => 'Goa',
        'city' => 'Goa',
    ],
    [
        'name' => 'Toddy',
        'image' => 'https://i.pinimg.com/736x/3b/cf/56/3bcf56e95ed086bccc21288baad8befe.jpg',
        'description' => 'Fermented palm sap, mildly alcoholic and popular in South India.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Alcoholic',
        'category' => 'Fermented Drink',
        'flavor_profile' => 'Fruity, Mild',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Kerala',
        'city' => 'Kochi',
    ],
    [
        'name' => 'Sharbat-e-Mohabbat',
        'image' => 'https://www.blendwithspices.com/wp-content/uploads/2018/07/mohabbat-ka-sharbat-recipe.jpg',
        'description' => 'Delhi summer drink with watermelon, rose syrup, and milk.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Fruit Drink',
        'flavor_profile' => 'Sweet, Fruity',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Delhi',
        'city' => 'Delhi',
    ],
    [
        'name' => 'Bel Sharbat',
        'image' => 'https://www.mydelicious-recipes.com/home/images/221_1200_1200/mydelicious-recipes-bel-sharbat',
        'description' => 'Cooling drink made from wood apple pulp, sugar, and water.',
        'cuisine_type' => 'Indian',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Fruit Drink',
        'flavor_profile' => 'Sweet, Earthy',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'Uttar Pradesh',
        'city' => 'Varanasi',
    ],
    // --- More International Drinks ---
    [
        'name' => 'Mojito',
        'image' => 'https://i.pinimg.com/originals/44/a3/a2/44a3a2b008e44dcb12fa564663daf7aa.jpg',
        'description' => 'Cuban cocktail with rum, lime, mint, sugar, and soda water.',
        'cuisine_type' => 'International',
        'drink_type' => 'Alcoholic',
        'category' => 'Cocktail',
        'flavor_profile' => 'Minty, Citrusy',
        'serving_temp' => 'Cold',
        'price_range' => '$$',
        'state' => 'Havana',
        'city' => 'Havana',
    ],
    [
        'name' => 'Piña Colada',
        'image' => 'https://www.onceuponachef.com/images/2023/07/pina-coladas-1200x1600.jpg',
        'description' => 'Tropical cocktail with rum, coconut cream, and pineapple juice.',
        'cuisine_type' => 'International',
        'drink_type' => 'Alcoholic',
        'category' => 'Cocktail',
        'flavor_profile' => 'Fruity, Creamy',
        'serving_temp' => 'Cold',
        'price_range' => '$$',
        'state' => 'San Juan',
        'city' => 'San Juan',
    ],
    [
        'name' => 'Sangria',
        'image' => 'https://www.bhg.com/thmb/G9yoBMaHBlP0aapEruIBSi6p34E=/1244x0/filters:no_upscale():strip_icc()/sangria-pitcher-RU237105-c9dfa3edb2ae4aa1b8cc535a3d6d2e0b.jpg',
        'description' => 'Spanish punch with red wine, fruit, and brandy.',
        'cuisine_type' => 'International',
        'drink_type' => 'Alcoholic',
        'category' => 'Wine Punch',
        'flavor_profile' => 'Fruity, Sweet',
        'serving_temp' => 'Cold',
        'price_range' => '$$',
        'state' => 'Andalusia',
        'city' => 'Seville',
    ],
    [
        'name' => 'Espresso',
        'image' => 'https://th.bing.com/th/id/OIP.dByRjIi_hqH-mFGU4-mkPwHaE8?w=278&h=185&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
        'description' => 'Strong, concentrated coffee served in small shots.',
        'cuisine_type' => 'International',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Coffee',
        'flavor_profile' => 'Strong, Bitter',
        'serving_temp' => 'Hot',
        'price_range' => '$',
        'state' => 'Lazio',
        'city' => 'Rome',
    ],
    [
        'name' => 'Cappuccino',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.V1JkuVX2RwpMMEqAEFJ2fQHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Espresso with steamed milk and a thick layer of foam.',
        'cuisine_type' => 'International',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Coffee',
        'flavor_profile' => 'Creamy, Strong',
        'serving_temp' => 'Hot',
        'price_range' => '$$',
        'state' => 'Lombardy',
        'city' => 'Milan',
    ],
    [
        'name' => 'Lemonade',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.k5zh_dLcRR26rew52dcUmQHaJ4?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Refreshing drink made with lemon juice, water, and sugar.',
        'cuisine_type' => 'International',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Lemonade',
        'flavor_profile' => 'Citrus, Sweet',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'California',
        'city' => 'Los Angeles',
    ],
    [
        'name' => 'Irish Coffee',
        'image' => 'https://th.bing.com/th/id/R.887c9f27fad5a8a2eb4c5bc99dd970c1?rik=QJxQi25%2bBbXYwg&riu=http%3a%2f%2fwww.bakingbeauty.net%2fwp-content%2fuploads%2f2016%2f02%2firish-coffee.jpg&ehk=JTe8O44cybawysW08xDws10%2f9%2b5F76a7mNMtXzEb6Yg%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Hot coffee, Irish whiskey, sugar, and cream.',
        'cuisine_type' => 'International',
        'drink_type' => 'Alcoholic',
        'category' => 'Coffee Cocktail',
        'flavor_profile' => 'Strong, Creamy',
        'serving_temp' => 'Hot',
        'price_range' => '$$',
        'state' => 'Dublin',
        'city' => 'Dublin',
    ],
    [
        'name' => 'Mai Tai',
        'image' => 'https://www.momontimeout.com/wp-content/uploads/2022/02/mai-tai-drink.jpeg',
        'description' => 'Rum, lime juice, and orange liqueur with tropical flavors.',
        'cuisine_type' => 'International',
        'drink_type' => 'Alcoholic',
        'category' => 'Cocktail',
        'flavor_profile' => 'Fruity, Citrusy',
        'serving_temp' => 'Cold',
        'price_range' => '$$',
        'state' => 'California',
        'city' => 'Oakland',
    ],
    [
        'name' => 'Hot Chocolate',
        'image' => 'https://feelgoodfoodie.net/wp-content/uploads/2021/11/how-to-make-hot-chocolate-7.jpg',
        'description' => 'Rich, creamy chocolate drink served hot.',
        'cuisine_type' => 'International',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Chocolate Drink',
        'flavor_profile' => 'Sweet, Creamy',
        'serving_temp' => 'Hot',
        'price_range' => '$',
        'state' => 'Zurich',
        'city' => 'Zurich',
    ],
    [
        'name' => 'Milkshake',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.JcAsXpgz4IScXjJrt6WBaQAAAA?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Blended ice cream, milk, and flavorings.',
        'cuisine_type' => 'International',
        'drink_type' => 'Non-Alcoholic',
        'category' => 'Milkshake',
        'flavor_profile' => 'Sweet, Creamy',
        'serving_temp' => 'Cold',
        'price_range' => '$',
        'state' => 'New York',
        'city' => 'New York City',
    ],
]; 