<?php
// fastfood_data.php
// Array of fast food dishes with detailed info
return [
    [
        'name' => 'Cheeseburger',
        'image' => 'https://cdn.pixabay.com/photo/2022/05/12/17/06/hamburger-7191902_1280.jpg',
        'description' => 'A juicy beef patty topped with cheddar cheese, lettuce, tomato, and pickles, all inside a toasted bun. The classic American comfort food, perfect for any meal.',
        'cuisine_type' => 'American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'California',
        'city' => 'Los Angeles',
    ],
    [
        'name' => 'Pepperoni Pizza',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.GlPf5HEBSNhuUeb8aMwsiwHaFh?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Classic pizza topped with spicy pepperoni, mozzarella cheese, and rich tomato sauce on a crispy crust. A favorite for pizza lovers everywhere.',
        'cuisine_type' => 'Italian-American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'New York',
        'city' => 'New York City',
    ],
    [
        'name' => 'French Fries',
        'image' => 'https://cdn.pixabay.com/photo/2024/01/12/15/05/food-8504111_1280.jpg',
        'description' => 'Crispy golden potato fries, lightly salted and perfect for dipping. A universal fast food side dish enjoyed by all ages.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack, Side',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Idaho',
        'city' => 'Boise',
    ],
    [
        'name' => 'Fried Chicken',
        'image' => 'https://cdn.pixabay.com/photo/2014/01/24/04/05/fried-chicken-250863_1280.jpg',
        'description' => 'Crispy, golden fried chicken with a juicy, tender inside. A southern classic loved for its crunch and flavor.',
        'cuisine_type' => 'American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'Kentucky',
        'city' => 'Louisville',
    ],
    [
        'name' => 'Chicken Nuggets',
        'image' => 'https://cdn.pixabay.com/photo/2014/01/16/01/48/chicken-nuggets-246180_1280.jpg',
        'description' => 'Tender chicken pieces coated in a crunchy golden breading. Perfect for dipping and snacking.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack, Lunch',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Georgia',
        'city' => 'Atlanta',
    ],
    [
        'name' => 'Hot Dog',
        'image' => 'https://cdn.pixabay.com/photo/2025/07/07/12/40/hot-dog-9701002_1280.png',
        'description' => 'Grilled sausage in a soft bun, topped with ketchup, mustard, and onions. A classic American street food.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack, Lunch',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Grilled',
        'state' => 'New York',
        'city' => 'New York City',
    ],
    [
        'name' => 'Tacos',
        'image' => 'https://cdn.pixabay.com/photo/2024/06/06/11/53/ai-generated-8812572_1280.jpg',
        'description' => 'Soft or crispy tortillas filled with seasoned meat, cheese, and fresh veggies. A Mexican favorite.',
        'cuisine_type' => 'Mexican',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'Texas',
        'city' => 'San Antonio',
    ],
    [
        'name' => 'Chicken Sandwich',
        'image' => 'https://cdn.pixabay.com/photo/2025/05/03/19/25/ai-generated-9576590_1280.png',
        'description' => 'Crispy chicken fillet, lettuce, and mayo in a toasted bun. A fast food staple.',
        'cuisine_type' => 'American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'Georgia',
        'city' => 'Atlanta',
    ],
    [
        'name' => 'Fish and Chips',
        'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Fish_and_chips_blackpool.jpg/1200px-Fish_and_chips_blackpool.jpg',
        'description' => 'Golden fried fish fillets served with crispy potato fries. A British classic.',
        'cuisine_type' => 'British',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'London',
        'city' => 'London',
    ],
    [
        'name' => 'Onion Rings',
        'image' => 'https://cdn.pixabay.com/photo/2018/09/11/16/16/food-3669928_1280.jpg',
        'description' => 'Crispy battered onion rings, perfect as a snack or side. Great for sharing.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack, Side',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Texas',
        'city' => 'Houston',
    ],
    [
        'name' => 'BBQ Ribs',
        'image' => 'https://cdn.pixabay.com/photo/2022/08/31/12/39/steak-7423232_1280.jpg',
        'description' => 'Tender pork ribs glazed with smoky barbecue sauce. A southern BBQ favorite.',
        'cuisine_type' => 'American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$$',
        'cooking_style' => 'Barbecued',
        'state' => 'Tennessee',
        'city' => 'Memphis',
    ],
    [
        'name' => 'Mozzarella Sticks',
        'image' => 'https://cdn.pixabay.com/photo/2018/02/12/07/54/mozzarella-3147643_1280.jpg',
        'description' => 'Crispy breaded mozzarella cheese sticks served with marinara sauce. Gooey and delicious.',
        'cuisine_type' => 'Italian-American',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'New Jersey',
        'city' => 'Newark',
    ],
    [
        'name' => 'Chili Cheese Fries',
        'image' => 'https://cdn.pixabay.com/photo/2021/03/29/17/11/chili-6134690_1280.jpg',
        'description' => 'Fries topped with spicy chili and melted cheese. A hearty, indulgent snack.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack, Side',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Texas',
        'city' => 'Dallas',
    ],
    [
        'name' => 'Burrito',
        'image' => 'https://cdn.pixabay.com/photo/2017/06/29/20/09/mexican-2456038_1280.jpg',
        'description' => 'Flour tortilla stuffed with rice, beans, meat, and salsa. A filling Mexican favorite.',
        'cuisine_type' => 'Mexican',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'California',
        'city' => 'San Diego',
    ],
    [
        'name' => 'Double Cheeseburger',
        'image' => 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80https://cdn.pixabay.com/photo/2022/08/31/10/17/burger-7422970_1280.jpg',
        'description' => 'Two beef patties, double cheese, lettuce, tomato, and pickles. Extra cheesy and filling.',
        'cuisine_type' => 'American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'Texas',
        'city' => 'Houston',
    ],
    [
        'name' => 'Veggie Pizza',
        'image' => 'https://cdn.pixabay.com/photo/2017/12/09/08/18/pizza-3007395_1280.jpg',
        'description' => 'Pizza topped with bell peppers, onions, olives, and mushrooms. A vegetarian delight.',
        'cuisine_type' => 'Italian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'California',
        'city' => 'San Francisco',
    ],
    [
        'name' => 'Spicy Chicken Wings',
        'image' => 'https://cdn.pixabay.com/photo/2022/05/25/07/48/hot-sour-charcoal-7219980_1280.jpg',
        'description' => 'Crispy wings tossed in spicy buffalo sauce. Perfect for parties and game nights.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Hot',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'New York',
        'city' => 'Buffalo',
    ],
    [
        'name' => 'Curly Fries',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.y-4UY4xlIyC5V7O-S1SvQAHaEv?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Seasoned spiral-cut fries, crispy and fun to eat. A twist on the classic fry.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack, Side',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Idaho',
        'city' => 'Boise',
    ],
    [
        'name' => 'Quesadilla',
        'image' => 'https://cdn.pixabay.com/photo/2019/03/04/13/00/quesadilla-4034046_1280.jpg',
        'description' => 'Grilled tortilla filled with melted cheese and your choice of meat or veggies. A Mexican comfort food.',
        'cuisine_type' => 'Mexican',
        'meal_type' => 'Lunch, Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Grilled',
        'state' => 'Texas',
        'city' => 'Austin',
    ],
    [
        'name' => 'Corn Dog',
        'image' => 'https://tse1.explicit.bing.net/th/id/OIP.ay4PO8z2fS9Ps0MVifwA2wAAAA?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Hot dog on a stick, dipped in cornmeal batter and fried. A fairground favorite.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Iowa',
        'city' => 'Des Moines',
    ],
    [
        'name' => 'Nachos',
        'image' => 'https://cdn.pixabay.com/photo/2014/02/14/22/15/nachos-266222_1280.jpg',
        'description' => 'Tortilla chips topped with cheese, jalapeños, salsa, and sour cream. Great for sharing.',
        'cuisine_type' => 'Mexican',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Baked',
        'state' => 'Texas',
        'city' => 'El Paso',
    ],
    [
        'name' => 'Sliders',
        'image' => 'https://tse4.mm.bing.net/th/id/OIP.2PIoVBnQq7skEZBFnUen8gHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Mini burgers with a variety of toppings. Perfect for parties and sharing.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'Ohio',
        'city' => 'Cleveland',
    ],
    [
        'name' => 'Margherita Pizza',
        'image' => 'https://cookieandkate.com/images/2021/07/classic-margherita-pizza.jpg',
        'description' => 'Classic pizza with tomato, mozzarella, and fresh basil. Simple and delicious.',
        'cuisine_type' => 'Italian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'Naples',
        'city' => 'Naples',
    ],
    [
        'name' => 'Buffalo Wings',
        'image' => 'https://www.thespruceeats.com/thmb/gXxOmyrw76vsaqjClOUm55cbZ0k=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/basic-buffalo-hot-wings-recipe-100937-hero-01-611327a035df408fa3771fe8970d8521.jpg',
        'description' => 'Spicy chicken wings served with blue cheese dip. A game day favorite.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Hot',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'New York',
        'city' => 'Buffalo',
    ],
    [
        'name' => 'Potato Wedges',
        'image' => 'https://images.pexels.com/photos/1439177/pexels-photo-1439177.jpeg',
        'description' => 'Thick-cut potato wedges, crispy on the outside and fluffy inside. A hearty snack or side.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack, Side',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Idaho',
        'city' => 'Boise',
    ],
    [
        'name' => 'Pulled Pork Sandwich',
        'image' => 'https://images.pexels.com/photos/1483769/pexels-photo-1483769.jpeg',
        'description' => 'Slow-cooked pulled pork in a soft bun with BBQ sauce. Smoky, tender, and flavorful.',
        'cuisine_type' => 'American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Barbecued',
        'state' => 'North Carolina',
        'city' => 'Charlotte',
    ],
    [
        'name' => 'Meatball Sub',
        'image' => 'https://tse1.explicit.bing.net/th/id/OIP.0OiOr46_Y1ck5EZN2KfO0QHaFj?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Sub roll filled with meatballs, marinara sauce, and melted cheese. Hearty and satisfying.',
        'cuisine_type' => 'Italian-American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'New Jersey',
        'city' => 'Jersey City',
    ],
    [
        'name' => 'Gyro',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.WSnieDngvn8gKoR5GgNWIgHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Pita bread filled with seasoned meat, veggies, and tzatziki sauce. A Greek street food staple.',
        'cuisine_type' => 'Greek',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'Athens',
        'city' => 'Athens',
    ],
    [
        'name' => 'Falafel Wrap',
        'image' => 'https://images.pexels.com/photos/5175621/pexels-photo-5175621.jpeg',
        'description' => 'Crispy falafel balls wrapped with veggies and tahini sauce. A vegetarian Middle Eastern favorite.',
        'cuisine_type' => 'Middle Eastern',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'Tel Aviv',
        'city' => 'Tel Aviv',
    ],
    [
        'name' => 'Chicken Shawarma',
        'image' => 'https://images.pexels.com/photos/6416559/pexels-photo-6416559.jpeg',
        'description' => 'Spiced chicken slices wrapped in pita with garlic sauce. A Middle Eastern street food classic.',
        'cuisine_type' => 'Middle Eastern',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'Beirut',
        'city' => 'Beirut',
    ],
    [
        'name' => 'Egg Roll',
        'image' => 'https://th.bing.com/th/id/OIP.kqcfnP2f1GK8KaF3tunvkwHaE8?w=282&h=188&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
        'description' => 'Crispy fried roll filled with veggies and meat. A popular Chinese takeout snack.',
        'cuisine_type' => 'Chinese',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Guangdong',
        'city' => 'Guangzhou',
    ],
    [
        'name' => 'Samosa',
        'image' => 'https://th.bing.com/th/id/OIP.Xp2RQVjyCr3kN1G8VhcK_wHaE_?w=277&h=187&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
        'description' => 'Fried pastry filled with spicy potatoes and peas. A beloved Indian snack.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Uttar Pradesh',
        'city' => 'Lucknow',
    ],
    [
        'name' => 'Spring Roll',
        'image' => 'https://images.pexels.com/photos/4001867/pexels-photo-4001867.jpeg',
        'description' => 'Crispy roll filled with vegetables and sometimes meat. A popular Asian appetizer.',
        'cuisine_type' => 'Asian',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Hong Kong',
        'city' => 'Hong Kong',
    ],
    [
        'name' => 'Paneer Tikka Wrap',
        'image' => 'https://thatspicychick.com/wp-content/uploads/2021/05/Paneer-Tikka-Kathi-Rolls-on-parchment-paper-sheet.jpg',
        'description' => 'Grilled paneer cubes wrapped with veggies and sauce. A North Indian favorite.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'Punjab',
        'city' => 'Amritsar',
    ],
    [
        'name' => 'Veggie Burger',
        'image' => 'https://www.noracooks.com/wp-content/uploads/2023/04/veggie-burgers-1-2.jpg',
        'description' => 'Burger with a patty made from vegetables and grains. A healthy and tasty alternative.',
        'cuisine_type' => 'American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'California',
        'city' => 'Los Angeles',
    ],
    [
        'name' => 'Chicken Popcorn',
        'image' => 'https://i0.wp.com/www.melissassouthernstylekitchen.com/wp-content/uploads/2019/06/EasyPopcornChicken003.jpg?fit=1484%2C2120&ssl=1',
        'description' => 'Bite-sized crispy fried chicken pieces. Perfect for snacking and sharing.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Kentucky',
        'city' => 'Louisville',
    ],
    [
        'name' => 'Pizza Pockets',
        'image' => 'https://www.tasteofhome.com/wp-content/uploads/2018/01/Pepperoni-Pizza-Pockets_EXPS_TOHAS22_7202_DR_03_31_3b.jpg',
        'description' => 'Mini pockets filled with pizza sauce, cheese, and toppings. A fun twist on pizza.',
        'cuisine_type' => 'Italian-American',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Baked',
        'state' => 'Illinois',
        'city' => 'Chicago',
    ],
    [
        'name' => 'Stuffed Paratha',
        'image' => 'https://biancazapatka.com/wp-content/uploads/2019/07/aloo-paratha-indian-potato-stuffed-flatbread-recipe-vegan.jpg',
        'description' => 'Indian flatbread stuffed with spiced potatoes or paneer. A North Indian breakfast favorite.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Breakfast, Lunch',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Pan-fried',
        'state' => 'Punjab',
        'city' => 'Ludhiana',
    ],
    [
        'name' => 'Chicken Kathi Roll',
        'image' => 'https://madscookhouse.com/wp-content/uploads/2021/02/Chicken-Kathi-Roll-1024x516.jpg',
        'description' => 'Spiced chicken rolled in a paratha with onions and chutney. A Kolkata street food classic.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Snack',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Pan-fried',
        'state' => 'West Bengal',
        'city' => 'Kolkata',
    ],
    [
        'name' => 'Paneer Burger',
        'image' => 'https://d36v5spmfzyapc.cloudfront.net/wp-content/uploads/2020/11/paneer-burger-4-848x424.jpg',
        'description' => 'Burger with a spicy paneer patty, lettuce, and sauce. A vegetarian delight.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'Delhi',
        'city' => 'Delhi',
    ],
    [
        'name' => 'Chicken Wrap',
        'image' => 'https://www.tasteofhome.com/wp-content/uploads/2018/01/Caesar-Chicken-Wraps_EXPS_CWAS18_21465_B04_05__5b.jpg',
        'description' => 'Grilled or fried chicken wrapped with veggies and sauce. A quick and tasty meal.',
        'cuisine_type' => 'American',
        'meal_type' => 'Lunch, Snack',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'California',
        'city' => 'San Diego',
    ],
    [
        'name' => 'Veggie Wrap',
        'image' => 'https://th.bing.com/th/id/OIP.U47SVA-gHE2tgswizLNTGgHaE8?w=303&h=202&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
        'description' => 'Wrap filled with fresh vegetables and tangy sauce. A healthy and refreshing option.',
        'cuisine_type' => 'American',
        'meal_type' => 'Lunch, Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Grilled',
        'state' => 'California',
        'city' => 'San Francisco',
    ],
    [
        'name' => 'Chicken Samosa',
        'image' => 'https://th.bing.com/th/id/OIP.0XBfGkU5BCpSHP6XUg2KEQHaHa?w=180&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
        'description' => 'Fried pastry filled with spicy chicken mince. A non-veg twist on the classic samosa.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Maharashtra',
        'city' => 'Mumbai',
    ],
    [
        'name' => 'Paneer Roll',
        'image' => 'https://vegrecipeskitchen.com/wp-content/uploads/2023/11/Paneer-roll-1024x585.jpg',
        'description' => 'Spiced paneer and veggies rolled in a flatbread. A popular Indian street food.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Pan-fried',
        'state' => 'Delhi',
        'city' => 'Delhi',
    ],
    [
        'name' => 'Chicken Tenders',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.hYAw9_bKfSiQfo0i5NwjiAHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Breaded and fried strips of chicken breast. Crispy on the outside, juicy inside.',
        'cuisine_type' => 'American',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'Texas',
        'city' => 'Houston',
    ],
    [
        'name' => 'Veggie Spring Roll',
        'image' => 'https://th.bing.com/th/id/R.bdbd489af567dcdac9833c75811a98a8?rik=65u2oKU3Gd7saA&riu=http%3a%2f%2f1.bp.blogspot.com%2f_4W04fJJ5sR8%2fTA1NHWHUwAI%2fAAAAAAAAA2k%2fw4WFq0n3eaE%2fs1600%2fIMG_2925.jpg&ehk=pNt5LGxhtOcwaq%2f5uTx8cM1Czv3QTqj1%2fv6ZI1jJSG8%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Crispy roll filled with mixed vegetables. A light and crunchy snack.',
        'cuisine_type' => 'Asian',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Bangkok',
        'city' => 'Bangkok',
    ],
    [
        'name' => 'Chicken Burger',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.x2vg5HgA4Rl9W12EEh1w1wHaF6?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Juicy chicken patty, lettuce, tomato, and mayo in a bun. A classic fast food favorite.',
        'cuisine_type' => 'American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'California',
        'city' => 'Los Angeles',
    ],
    [
        'name' => 'Paneer Pizza',
        'image' => 'https://th.bing.com/th/id/R.f186a871c218e3929dfd69fac7b69fc7?rik=E2mt7l96F7lGOg&riu=http%3a%2f%2fwww.rajcakepalace.in%2fwp-content%2fuploads%2f2021%2f03%2f1e336162c6172fdb30da0449f1bfd71d.jpg&ehk=pWXKibRNm%2f0QsAk2VOSltH0qzgWkERilnG3UgUHionI%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Pizza topped with paneer cubes, onions, and capsicum. An Indian twist on pizza.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'Maharashtra',
        'city' => 'Mumbai',
    ],
    [
        'name' => 'Chicken Pizza',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.DFBdtlszPpuTwBfNdN2rmQHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Pizza topped with spicy chicken, onions, and cheese. A meaty delight.',
        'cuisine_type' => 'Italian-American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'New York',
        'city' => 'New York City',
    ],
    [
        'name' => 'Veggie Sub',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.tqIV7_qHMn-Lg7jCAX8ySwHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Sub sandwich loaded with fresh veggies and cheese. A healthy and filling option.',
        'cuisine_type' => 'American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Fresh',
        'state' => 'California',
        'city' => 'San Francisco',
    ],
    [
        'name' => 'Chicken Sub',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.Z39jAc1Uo_9XqJnKDNFpiwHaE7?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Sub sandwich filled with grilled chicken and veggies. Protein-packed and tasty.',
        'cuisine_type' => 'American',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'Texas',
        'city' => 'Houston',
    ],
    [
        'name' => 'Paneer Sub',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.b5Rj3ywmzwfPu1oDK6v0egHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Sub sandwich with spicy paneer and veggies. A vegetarian sub with Indian flavors.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Fresh',
        'state' => 'Delhi',
        'city' => 'Delhi',
    ],
    // Add more dishes as needed...
]; 