<?php
// nutrional_data.php
// Array of nutritional/healthy food items with detailed info
return [
    // --- Indian Nutritional Dishes (60%) ---
    [
        'name' => 'Moong Dal Chilla',
        'image' => 'https://tse4.mm.bing.net/th/id/OIP.UJduCIFKVgtQPxvL4fidxwHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Savory pancakes made from ground moong dal, rich in protein and fiber.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Breakfast, Snack',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'High Protein, Low Fat',
        'calories' => 180,
        'state' => 'Delhi',
        'city' => 'Delhi',
    ],
    [
        'name' => 'Palak Paneer',
        'image' => 'https://www.indianveggiedelight.com/wp-content/uploads/2017/10/palak-paneer-featured.jpg',
        'description' => 'Cottage cheese cubes in a spinach gravy, loaded with iron and calcium.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'High Protein, Iron Rich',
        'calories' => 320,
        'state' => 'Punjab',
        'city' => 'Amritsar',
    ],
    [
        'name' => 'Dhokla',
        'image' => 'https://storables.com/wp-content/uploads/2023/08/how-to-make-dhokla-without-steamer-1693210659.jpg',
        'description' => 'Steamed savory cake made from fermented rice and chickpea batter.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Breakfast, Snack',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'Low Calorie, Probiotic',
        'calories' => 150,
        'state' => 'Gujarat',
        'city' => 'Ahmedabad',
    ],
    [
        'name' => 'Ragi Roti',
        'image' => 'https://tse4.mm.bing.net/th/id/OIP.lzk_berQuSCvkd8S5a3QpwHaJ4?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Flatbread made from finger millet flour, high in calcium and fiber.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Breakfast, Lunch',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'Calcium Rich, Gluten Free',
        'calories' => 120,
        'state' => 'Karnataka',
        'city' => 'Bangalore',
    ],
    [
        'name' => 'Sprouted Moong Salad',
        'image' => 'https://www.caramelandspice.com/wp-content/uploads/2022/11/9E74A04F-ED1B-4CD3-A587-EAB721D29110_1_105_c-e1669802775512.jpg',
        'description' => 'Salad of sprouted green gram, tomatoes, onions, and lemon juice.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Salad',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'High Protein, High Fiber',
        'calories' => 90,
        'state' => 'Maharashtra',
        'city' => 'Mumbai',
    ],
    [
        'name' => 'Vegetable Upma',
        'image' => 'https://myfoodstory.com/wp-content/uploads/2022/11/Vegetable-Upma-2-1024x1536.jpg',
        'description' => 'Semolina cooked with vegetables and spices, a light and nutritious breakfast.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Breakfast',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'Low Calorie, High Fiber',
        'calories' => 210,
        'state' => 'Tamil Nadu',
        'city' => 'Chennai',
    ],
    [
        'name' => 'Oats Idli',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.4I9xrQeV8wZ9yDcOsJ45rAHaLU?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Steamed cakes made from oats and lentils, low in calories and high in fiber.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Breakfast',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'Low Calorie, High Fiber',
        'calories' => 110,
        'state' => 'Karnataka',
        'city' => 'Bangalore',
    ],
    [
        'name' => 'Bhindi Masala',
        'image' => 'https://i.pinimg.com/originals/be/5d/6d/be5d6dac6cf9a17b16eadfad13976343.jpg',
        'description' => 'Okra stir-fried with onions and spices, rich in vitamins and fiber.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'High Fiber, Vitamin Rich',
        'calories' => 140,
        'state' => 'Uttar Pradesh',
        'city' => 'Lucknow',
    ],
    [
        'name' => 'Tandoori Chicken',
        'image' => 'https://mapupa.com/wp-content/uploads/2024/01/Tandoori-Chicken.webp',
        'description' => 'Chicken marinated in yogurt and spices, grilled for a low-fat protein meal.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'nutritional_benefit' => 'High Protein, Low Fat',
        'calories' => 260,
        'state' => 'Punjab',
        'city' => 'Amritsar',
    ],
    [
        'name' => 'Baingan Bharta',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.72l-sxKxkVbe3W47PlrQGwHaKf?r=0&rs=1&pid=ImgDetMain&o=7&rm
        =3',
        'description' => 'Roasted eggplant mashed and cooked with tomatoes and spices.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'Low Calorie, High Fiber',
        'calories' => 120,
        'state' => 'Maharashtra',
        'city' => 'Pune',
    ],
    [
        'name' => 'Kuttu Ka Dosa',
        'image' => 'https://images.herzindagi.info/image/2022/Mar/kuttu-ka-dosa-ready.jpg',
        'description' => 'Buckwheat crepes, gluten-free and rich in fiber, popular during fasting.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Breakfast, Snack',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'Gluten Free, High Fiber',
        'calories' => 160,
        'state' => 'Uttar Pradesh',
        'city' => 'Varanasi',
    ],
    [
        'name' => 'Lauki Chana Dal',
        'image' => 'https://th.bing.com/th/id/R.20b0c07b7c5b1770bba79f8fb0117bc7?rik=vAB7XmlJIoxkFQ&riu=http%3a%2f%2fwww.ruchiskitchen.com%2fwp-content%2fuploads%2f2014%2f06%2fchana-dal-with-lauki-recipe.jpg&ehk=mFvPd3WlGsd942PuAjmqoBFUR3ButDWB0QpfYsFRdfg%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Bottle gourd cooked with Bengal gram, low in calories and high in protein.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'Low Calorie, High Protein',
        'calories' => 130,
        'state' => 'Bihar',
        'city' => 'Patna',
    ],
    [
        'name' => 'Methi Thepla',
        'image' => 'https://somethingiscooking.com/wp-content/uploads/2017/01/MethiThepla2.jpg',
        'description' => 'Whole wheat flatbread with fenugreek leaves, rich in iron and fiber.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Breakfast, Snack',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'Iron Rich, High Fiber',
        'calories' => 170,
        'state' => 'Gujarat',
        'city' => 'Surat',
    ],
    [
        'name' => 'Brown Rice Pulao',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.8G-cfXSUU_zyNAUFu822SAHaEM?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Brown rice cooked with assorted vegetables and mild spices.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'Whole Grain, High Fiber',
        'calories' => 220,
        'state' => 'West Bengal',
        'city' => 'Kolkata',
    ],
    [
        'name' => 'Rajma Salad',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.vFBHr9CBeAgh2IDwf6zOAgHaIb?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Kidney beans tossed with onions, tomatoes, and lemon juice.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Salad, Snack',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'High Protein, High Fiber',
        'calories' => 140,
        'state' => 'Himachal Pradesh',
        'city' => 'Shimla',
    ],
    [
        'name' => 'Paneer Bhurji',
        'image' => 'https://vegecravings.com/wp-content/uploads/2022/04/Paneer-Bhurji-Recipe-Step-By-Step-Instructions.jpg',
        'description' => 'Scrambled cottage cheese with vegetables, high in protein and calcium.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Breakfast, Lunch',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'High Protein, Calcium Rich',
        'calories' => 250,
        'state' => 'Delhi',
        'city' => 'Delhi',
    ],
    [
        'name' => 'Carrot Halwa (Low Sugar)',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.P4Bpr5bA5h9WkUlVDakyUQHaHi?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Classic carrot pudding made with less sugar and low-fat milk.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Dessert',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'Vitamin A, Low Sugar',
        'calories' => 180,
        'state' => 'Punjab',
        'city' => 'Ludhiana',
    ],
    [
        'name' => 'Vegetable Stew',
        'image' => 'https://lifemadesweeter.com/wp-content/uploads/Whole30-Vegetable-Stew-Recipe-Photo-Vegan-Keto-Whole30.jpg',
        'description' => 'Mixed vegetables simmered in coconut milk, light and nutritious.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'Vitamin Rich, Dairy Free',
        'calories' => 160,
        'state' => 'Kerala',
        'city' => 'Kochi',
    ],
    [
        'name' => 'Chana Chaat',
        'image' => 'https://www.madhuseverydayindian.com/wp-content/uploads/2021/05/chana-chaat-with-yogurt.jpg',
        'description' => 'Spiced chickpea salad with onions, tomatoes, and coriander.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Salad',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'High Protein, High Fiber',
        'calories' => 120,
        'state' => 'Uttar Pradesh',
        'city' => 'Kanpur',
    ],
    [
        'name' => 'Idiyappam with Vegetable Kurma',
        'image' => 'https://i.ytimg.com/vi/5E3EcXbPkcI/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-DoACsAiKAgwIABABGD0gZSgWMA8=&amp;rs=AOn4CLBtJIJEVfPvz5IIWmaqIOlkSRA1IQ',
        'description' => 'Steamed rice noodles served with a medley of vegetables in coconut gravy.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Breakfast, Dinner',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'Gluten Free, Vitamin Rich',
        'calories' => 210,
        'state' => 'Tamil Nadu',
        'city' => 'Madurai',
    ],
    [
        'name' => 'Masoor Dal Soup',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.dhShimixcIY6RxVDMftTpwHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Red lentil soup, light and protein-rich, flavored with Indian spices.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Soup, Dinner',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'High Protein, Low Fat',
        'calories' => 110,
        'state' => 'Madhya Pradesh',
        'city' => 'Bhopal',
    ],
    [
        'name' => 'Kadhi Pakora (Baked)',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.2CltCzxjl8jtFe0NzLb_QQHaGL?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Yogurt-based curry with baked gram flour dumplings, less oil.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'Probiotic, Low Fat',
        'calories' => 190,
        'state' => 'Rajasthan',
        'city' => 'Jaipur',
    ],
    // --- International Nutritional Dishes (40%) ---
    [
        'name' => 'Grilled Salmon',
        'image' => 'https://www.cookingclassy.com/wp-content/uploads/2018/05/grilled-salmon-3.jpg',
        'description' => 'Rich in omega-3, served with steamed veggies and lemon.',
        'cuisine_type' => 'International',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'nutritional_benefit' => 'Omega-3, High Protein',
        'calories' => 350,
        'state' => 'Alaska',
        'city' => 'Anchorage',
    ],
    [
        'name' => 'Quinoa Salad',
        'image' => 'https://foolproofliving.com/wp-content/uploads/2021/09/Quinoa-Tabbouleh-Salad-recipe.jpg',
        'description' => 'Protein-packed quinoa with cherry tomatoes, cucumber, and feta.',
        'cuisine_type' => 'International',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'High Protein, Gluten Free',
        'calories' => 220,
        'state' => 'California',
        'city' => 'San Francisco',
    ],
    [
        'name' => 'Avocado Toast',
        'image' => 'https://www.jessicagavin.com/wp-content/uploads/2020/07/avocado-toast-11.jpg',
        'description' => 'Whole grain bread topped with smashed avocado and seeds.',
        'cuisine_type' => 'International',
        'meal_type' => 'Breakfast, Snack',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'Healthy Fats, High Fiber',
        'calories' => 190,
        'state' => 'California',
        'city' => 'Los Angeles',
    ],
    [
        'name' => 'Greek Yogurt Parfait',
        'image' => 'https://simplyhomecooked.com/wp-content/uploads/2015/07/berry-parfait-4.jpg',
        'description' => 'Layers of Greek yogurt, berries, and granola for a healthy start.',
        'cuisine_type' => 'International',
        'meal_type' => 'Breakfast',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'Probiotic, High Protein',
        'calories' => 180,
        'state' => 'New York',
        'city' => 'New York City',
    ],
    [
        'name' => 'Chicken Caesar Salad (Light)',
        'image' => 'https://s23209.pcdn.co/wp-content/uploads/2023/01/220905_DD_Chx-Caesar-Salad_051-1365x2048.jpg',
        'description' => 'Grilled chicken breast, romaine lettuce, and light Caesar dressing.',
        'cuisine_type' => 'International',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Non-Vegetarian',
        'nutritional_benefit' => 'High Protein, Low Fat',
        'calories' => 260,
        'state' => 'California',
        'city' => 'San Diego',
    ],
    [
        'name' => 'Lentil & Veggie Buddha Bowl',
        'image' => 'https://tse4.mm.bing.net/th/id/OIP.ZbIlOY2YTGgAEpseK3wxVwHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'A bowl of lentils, roasted veggies, and brown rice.',
        'cuisine_type' => 'International',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'High Fiber, Plant Protein',
        'calories' => 230,
        'state' => 'Oregon',
        'city' => 'Portland',
    ],
    [
        'name' => 'Egg White Omelette',
        'image' => 'https://th.bing.com/th/id/R.c6316054adfa1e7a1119c7a2b5b476a7?rik=gIAwKD7y6%2b5aAA&riu=http%3a%2f%2fwww.improvoven.com%2fwp-content%2fuploads%2f2016%2f06%2fegg-white-omelette7-768x1154.jpg&ehk=VtB2OZOwzpip2CoRhk%2f9tIktm4Oe3WA7%2fpsNvfEhvqU%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Omelette made with egg whites, spinach, and tomatoes.',
        'cuisine_type' => 'International',
        'meal_type' => 'Breakfast',
        'dietary_preference' => 'Vegetarian',
        'nutritional_benefit' => 'Low Calorie, High Protein',
        'calories' => 120,
        'state' => 'Texas',
        'city' => 'Austin',
    ],
    [
        'name' => 'Zucchini Noodles with Pesto',
        'image' => 'https://kalejunkie.com/wp-content/uploads/2022/05/10-MinuteVeganPistachioPestoZucchiniPesto_Shot5_17-1.jpg',
        'description' => 'Spiralized zucchini tossed in homemade basil pesto.',
        'cuisine_type' => 'International',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'Low Carb, Vitamin Rich',
        'calories' => 140,
        'state' => 'Italy',
        'city' => 'Rome',
    ],
    [
        'name' => 'Tofu Stir Fry',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.ZaDDNErc2UQmBlyS2tGYMQHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Tofu cubes stir-fried with colorful vegetables and soy sauce.',
        'cuisine_type' => 'International',
        'meal_type' => 'Lunch, Dinner',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'Plant Protein, Low Fat',
        'calories' => 180,
        'state' => 'China',
        'city' => 'Shanghai',
    ],
    [
        'name' => 'Berry Chia Pudding',
        'image' => 'https://tse1.explicit.bing.net/th/id/OIP.Zx2fSSM6xA5HO6LbC86DuwHaJ3?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Chia seeds soaked in almond milk, topped with fresh berries.',
        'cuisine_type' => 'International',
        'meal_type' => 'Breakfast, Dessert',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'Omega-3, High Fiber',
        'calories' => 160,
        'state' => 'Canada',
        'city' => 'Toronto',
    ],
    [
        'name' => 'Baked Sweet Potato Fries',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.q9nenmBwlZr7ec5jmB4U2QHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Sweet potatoes baked until crisp, a healthy alternative to fries.',
        'cuisine_type' => 'International',
        'meal_type' => 'Snack, Side',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'Vitamin A, Low Fat',
        'calories' => 130,
        'state' => 'USA',
        'city' => 'Dallas',
    ],
    [
        'name' => 'Miso Soup',
        'image' => 'https://www.desidakaar.com/wp-content/uploads/2019/12/miso-soup-horizontal-jpg-1529350400-1536x1024.jpg',
        'description' => 'Traditional Japanese soup with tofu, seaweed, and miso paste.',
        'cuisine_type' => 'International',
        'meal_type' => 'Soup, Dinner',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'Probiotic, Low Calorie',
        'calories' => 90,
        'state' => 'Japan',
        'city' => 'Tokyo',
    ],
    [
        'name' => 'Falafel Wrap',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.M5nE-OVrptUqUT7oMa1WEQHaJQ?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Chickpea patties wrapped in whole wheat pita with veggies.',
        'cuisine_type' => 'International',
        'meal_type' => 'Lunch, Snack',
        'dietary_preference' => 'Vegan',
        'nutritional_benefit' => 'High Protein, High Fiber',
        'calories' => 210,
        'state' => 'Israel',
        'city' => 'Tel Aviv',
    ],
]; 