<?php
// snacks_data.php
// Array of snack dishes with detailed info
return [
    // --- Indian Snacks (70%) ---
    [
        'name' => 'Samosa',
        'image' => 'https://i1.wp.com/vegecravings.com/wp-content/uploads/2017/03/samosa-recipe-step-by-step-instructions.jpg?fit=1801%2C1717&ssl=1',
        'description' => 'Crispy pastry filled with spicy potatoes and peas. A classic Indian street snack.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Uttar Pradesh',
        'city' => 'Varanasi',
    ],
    [
        'name' => 'Vada Pav',
        'image' => 'https://www.samosasingh.com/wp-content/uploads/2020/09/VadaPav1-600x400.jpg',
        'description' => 'Spicy potato fritter in a bun, served with chutneys. Mumbai’s favorite snack.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Hot',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Maharashtra',
        'city' => 'Mumbai',
    ],
    [
        'name' => 'Dhokla',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.W2G_SeUBPh8ez5JhMIpUnwHaGO?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Steamed, spongy snack made from fermented rice and chickpea batter.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Breakfast',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Steamed',
        'state' => 'Gujarat',
        'city' => 'Ahmedabad',
    ],
    [
        'name' => 'Pav Bhaji',
        'image' => 'https://www.cubesnjuliennes.com/wp-content/uploads/2020/07/Instant-Pot-Mumbai-Pav-Bhaji-Recipe.jpg',
        'description' => 'Spicy mashed vegetables served with buttered bread rolls.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Dinner',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Griddled',
        'state' => 'Maharashtra',
        'city' => 'Mumbai',
    ],
    [
        'name' => 'Aloo Tikki',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.lLDlBzPq3tU3MKCp5wF5xgHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Crispy potato patties spiced with Indian herbs, often served with chutneys.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Delhi',
        'city' => 'Delhi',
    ],
    [
        'name' => 'Pani Puri',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.pGdwZ1gWkQy6D6TwA7hOowHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Hollow crispy puris filled with spicy, tangy water and potatoes.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Hot',
        'price_range' => '$',
        'cooking_style' => 'Assembled',
        'state' => 'West Bengal',
        'city' => 'Kolkata',
    ],
    [
        'name' => 'Pakora',
        'image' => 'https://th.bing.com/th/id/R.5fb78cef3a6b2b1badc917d2798a86f0?rik=pMm%2bIoYNo%2bi7rw&riu=http%3a%2f%2fwww.archanaskitchen.com%2fimages%2farchanaskitchen%2f1-Author%2fShaheen_Ali%2fVeg_Noodle_Pakora.jpg&ehk=wKCzNj%2bMX%2bVUdeQskTZACMTHCIBXEn02zNDiBZGAEjU%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Vegetables dipped in chickpea batter and deep-fried until golden.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Punjab',
        'city' => 'Amritsar',
    ],
    [
        'name' => 'Kachori',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.suS4sAXEXpK9KNpKkxWQEAHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Flaky, deep-fried pastry filled with spicy lentils or peas.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Rajasthan',
        'city' => 'Jaipur',
    ],
    [
        'name' => 'Dabeli',
        'image' => 'https://i.pinimg.com/originals/e9/ee/40/e9ee40bf2a7303d37ffbd6c6676ed419.jpg',
        'description' => 'Spicy potato mixture in a bun, topped with pomegranate and sev.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Griddled',
        'state' => 'Gujarat',
        'city' => 'Bhuj',
    ],
    [
        'name' => 'Mysore Bonda',
        'image' => 'https://tse4.mm.bing.net/th/id/OIP.wfNCOJZe0MFfy-xkQUHevwHaFR?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Deep-fried dumplings made from flour, yogurt, and spices.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Breakfast',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Karnataka',
        'city' => 'Mysore',
    ],
    [
        'name' => 'Chana Chaat',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.oE-kjnhxb6PxUmsTreyzagHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Tangy, spicy chickpea salad with onions, tomatoes, and chutneys.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Assembled',
        'state' => 'Delhi',
        'city' => 'Delhi',
    ],
    [
        'name' => 'Murukku',
        'image' => 'https://i.pinimg.com/originals/da/f0/44/daf044cb3dc8a889652aa893fb519644.jpg',
        'description' => 'Crunchy, spiral-shaped snack made from rice flour and spices.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Tamil Nadu',
        'city' => 'Chennai',
    ],
    [
        'name' => 'Bhujia',
        'image' => 'https://www.whiskaffair.com/wp-content/uploads/2018/09/Aloo-Bhujia-1-3.jpg',
        'description' => 'Spicy, crispy noodle-like snack made from gram flour.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Rajasthan',
        'city' => 'Bikaner',
    ],
    [
        'name' => 'Banana Chips',
        'image' => 'https://www.kp-sugargroup.com/_sys/wp-content/uploads/2021/04/8-1.jpg',
        'description' => 'Thinly sliced bananas deep-fried until crisp, a South Indian favorite.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Kerala',
        'city' => 'Kochi',
    ],
    [
        'name' => 'Sev Puri',
        'image' => 'https://i0.wp.com/sinfully-desilicious.com/wp-content/uploads/2020/09/8f-1-edited.jpg?w=2278&ssl=1',
        'description' => 'Crispy puris topped with potatoes, chutneys, onions, and sev.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Assembled',
        'state' => 'Maharashtra',
        'city' => 'Mumbai',
    ],
    [
        'name' => 'Moong Dal Chilla',
        'image' => 'https://www.whiskaffair.com/wp-content/uploads/2020/07/Moong-Dal-Chilla-2-1.jpg',
        'description' => 'Savory pancakes made from ground moong dal, spiced and pan-fried.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Breakfast',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Pan-fried',
        'state' => 'Uttar Pradesh',
        'city' => 'Lucknow',
    ],
    [
        'name' => 'Sabudana Vada',
        'image' => 'https://www.funfoodfrolic.com/wp-content/uploads/2020/08/Sabudana-Vada-Thumbnail-Blog.jpg',
        'description' => 'Crispy fritters made from sago, potatoes, and peanuts, popular during fasting.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Maharashtra',
        'city' => 'Pune',
    ],
    [
        'name' => 'Paneer Pakora',
        'image' => 'https://www.secondrecipe.com/wp-content/uploads/2024/12/paneer-pakora-air-fryer.jpg',
        'description' => 'Cubes of paneer dipped in spiced gram flour batter and deep-fried.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Punjab',
        'city' => 'Ludhiana',
    ],
    [
        'name' => 'Bread Pakora',
        'image' => 'https://recipes.timesofindia.com/thumb/53240499.cms?imgsize=297578&width=800&height=800',
        'description' => 'Bread slices stuffed with spicy potatoes, dipped in batter and fried.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Breakfast',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Delhi',
        'city' => 'Delhi',
    ],
    [
        'name' => 'Mathri',
        'image' => 'https://th.bing.com/th/id/R.1348b6703855e742736c3764fb62deeb?rik=XKLEW%2fBQz2Ed%2bg&riu=http%3a%2f%2f2.bp.blogspot.com%2f-FxYqMMfoW8c%2fUFxwbMKjNjI%2fAAAAAAAAF5Q%2fcDcs_OjV2fQ%2fs1600%2fmathri-22.jpg&ehk=3dv%2fArf4XrcEge6ZzFva1LngiCmY39miPOlkRUhMvRA%3d&risl=&pid=ImgRaw&r=0',
        'description' => 'Crispy, flaky crackers made from flour and spices, popular in North India.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Rajasthan',
        'city' => 'Jaipur',
    ],
    [
        'name' => 'Khakhra',
        'image' => 'https://rahegujaratisnacks.com/wp-content/uploads/2023/06/Methi-Masala-Khakhra.jpg',
        'description' => 'Thin, crispy flatbreads made from whole wheat flour, roasted to perfection.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Breakfast',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Roasted',
        'state' => 'Gujarat',
        'city' => 'Surat',
    ],
    [
        'name' => 'Sooji/Rava Upma',
        'image' => 'https://vismaifood.com/storage/app/uploads/public/605/d6d/a40/605d6da40a167890769224.jpg',
        'description' => 'Savory South Indian breakfast made from semolina, veggies, and spices.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Breakfast',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Cooked',
        'state' => 'Karnataka',
        'city' => 'Bangalore',
    ],
    [
        'name' => 'Idli',
        'image' => 'https://static.toiimg.com/photo/68631114.cms',
        'description' => 'Soft, steamed rice cakes, a staple South Indian snack and breakfast.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Breakfast',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Steamed',
        'state' => 'Tamil Nadu',
        'city' => 'Chennai',
    ],
    [
        'name' => 'Medu Vada',
        'image' => 'https://images.slurrp.com/prod/recipe_images/transcribe/breakfast/Medu-Vada.webp',
        'description' => 'Crispy, savory doughnuts made from urad dal, served with chutney.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Breakfast',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Tamil Nadu',
        'city' => 'Chennai',
    ],
    [
        'name' => 'Poha',
        'image' => 'https://i1.wp.com/shikhaskitchen.com/wp-content/uploads/2020/09/IMG-3528-scaled.jpg?zoom=3&resize=800%2C530&ssl=1',
        'description' => 'Flattened rice cooked with onions, potatoes, and spices, a light snack.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Breakfast',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Cooked',
        'state' => 'Madhya Pradesh',
        'city' => 'Indore',
    ],
    [
        'name' => 'Egg Puff',
        'image' => 'https://www.iwmbuzz.com/wp-content/uploads/2022/05/want-to-try-something-new-make-these-egg-puffs-at-home-2.jpg',
        'description' => 'Flaky pastry filled with spiced boiled egg, a bakery favorite.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Baked',
        'state' => 'Kerala',
        'city' => 'Kozhikode',
    ],
    [
        'name' => 'Chicken 65',
        'image' => 'https://biryanibowlwa.com/wp-content/uploads/2021/05/Chicken-65.jpg',
        'description' => 'Spicy, deep-fried chicken bites, a South Indian bar snack.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Hot',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'Tamil Nadu',
        'city' => 'Chennai',
    ],
    [
        'name' => 'Fish Cutlet',
        'image' => 'https://mariasmenu.com/wp-content/uploads/Kerala-Fish-Cutlet-.png',
        'description' => 'Spiced fish patties, breaded and deep-fried, popular in coastal India.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'Goa',
        'city' => 'Panaji',
    ],
    [
        'name' => 'Vegetable Puff',
        'image' => 'https://tse2.mm.bing.net/th/id/OIP.R1Yonl1euQiedfJT7qOYawHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Flaky pastry filled with spiced mixed vegetables.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Baked',
        'state' => 'West Bengal',
        'city' => 'Kolkata',
    ],
    [
        'name' => 'Chakli',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.eWmiC-YrnFvQ7pRZjCx0BwHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Spiral-shaped, crunchy snack made from rice flour and spices.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Maharashtra',
        'city' => 'Mumbai',
    ],
    [
        'name' => 'Gobi Manchurian',
        'image' => 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/07/veg-manchurian.jpg',
        'description' => 'Crispy cauliflower tossed in spicy Indo-Chinese sauce.',
        'cuisine_type' => 'Indo-Chinese',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Hot',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'Karnataka',
        'city' => 'Bangalore',
    ],
    [
        'name' => 'Paneer Tikka',
        'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80https://www.cookforindia.com/wp-content/uploads/2016/08/Paneer-Tikka-_LR.jpg',
        'description' => 'Chunks of paneer marinated in spices and grilled.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Grilled',
        'state' => 'Punjab',
        'city' => 'Amritsar',
    ],
    [
        'name' => 'Corn Chaat',
        'image' => 'https://aartimadan.com/wp-content/uploads/2020/10/corn-chaat.jpg',
        'description' => 'Spicy, tangy chaat made with sweet corn, onions, and spices.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Assembled',
        'state' => 'Delhi',
        'city' => 'Delhi',
    ],
    [
        'name' => 'Rajma Galouti Kebab',
        'image' => 'https://img-global.cpcdn.com/recipes/4f4744c0e18aaead/680x482cq70/rajma-galouti-kebab-recipe-main-photo.jpg',
        'description' => 'Soft, melt-in-mouth kebabs made from kidney beans and spices.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Pan-fried',
        'state' => 'Uttar Pradesh',
        'city' => 'Lucknow',
    ],
    [
        'name' => 'Batata Vada',
        'image' => 'https://3.bp.blogspot.com/-y7SvH-R5i2Y/V9h8brMvgTI/AAAAAAAAPnU/52EaRARQ_BA9bTgTk_Vq4m_onQ6gXPOdgCLcB/s1600/batatavadarecipe.jpg',
        'description' => 'Spicy mashed potato balls dipped in batter and deep-fried.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Maharashtra',
        'city' => 'Mumbai',
    ],
    [
        'name' => 'Kathi Roll',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.ed-qZPutpc6y32omQss6OAHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Flatbread rolled with spiced fillings like paneer, chicken, or veggies.',
        'cuisine_type' => 'Indian',
        'meal_type' => 'Snack, Lunch',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Griddled',
        'state' => 'West Bengal',
        'city' => 'Kolkata',
    ],
    // --- World Snacks (30%) ---
    [
        'name' => 'Empanada',
        'image' => 'https://www.thespruceeats.com/thmb/JVCmfjzpaubbpywGrtgRpcQMgJA=/4494x3000/filters:fill(auto,1)/chilean-style-beef-empanadas-3029728-hero-01-c2bcd8b6df1c4ecf8aa1145d25df55b8.jpg',
        'description' => 'Pastry filled with meat or vegetables, popular in Latin America.',
        'cuisine_type' => 'Latin American',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Medium',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'Buenos Aires',
        'city' => 'Buenos Aires',
    ],
    [
        'name' => 'Arancini',
        'image' => 'https://i0.wp.com/tonibrancatisano.com/wp-content/uploads/2018/08/G.jpg?w=3600',
        'description' => 'Italian rice balls stuffed with cheese or meat, breaded and fried.',
        'cuisine_type' => 'Italian',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Fried',
        'state' => 'Sicily',
        'city' => 'Palermo',
    ],
    [
        'name' => 'Baozi',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.qJGw8K0uV2jQJtXR15fAWAHaFL?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Chinese steamed buns with savory fillings.',
        'cuisine_type' => 'Chinese',
        'meal_type' => 'Snack, Breakfast',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Steamed',
        'state' => 'Guangdong',
        'city' => 'Guangzhou',
    ],
    [
        'name' => 'Arepa',
        'image' => 'https://eldiariony.com/wp-content/uploads/sites/2/2019/12/canva-venezuelan-typical-food-arepa.jpg?quality=80&strip=all',
        'description' => 'Cornmeal cakes from Venezuela and Colombia, filled with cheese or meat.',
        'cuisine_type' => 'South American',
        'meal_type' => 'Snack, Breakfast',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Griddled',
        'state' => 'Caracas',
        'city' => 'Caracas',
    ],
    [
        'name' => 'Onigiri',
        'image' => 'https://tse3.mm.bing.net/th/id/OIP.P__zYilaZQrhezKSUNqEnwHaEK?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Japanese rice balls, often wrapped in seaweed and filled with savory ingredients.',
        'cuisine_type' => 'Japanese',
        'meal_type' => 'Snack, Lunch',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Assembled',
        'state' => 'Tokyo',
        'city' => 'Tokyo',
    ],
    [
        'name' => 'Tostones',
        'image' => 'https://www.cook2eatwell.com/wp-content/uploads/2018/07/Tostones-9.jpg',
        'description' => 'Twice-fried plantain slices, a crunchy Latin American snack.',
        'cuisine_type' => 'Caribbean',
        'meal_type' => 'Snack, Side',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'San Juan',
        'city' => 'San Juan',
    ],
    [
        'name' => 'Pão de Queijo',
        'image' => 'https://tse1.explicit.bing.net/th/id/OIP.zWgj7pHSvbtDrMWY8IjzsQHaFi?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Brazilian cheese bread, chewy and cheesy bite-sized snacks.',
        'cuisine_type' => 'Brazilian',
        'meal_type' => 'Snack, Breakfast',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'Minas Gerais',
        'city' => 'Belo Horizonte',
    ],
    [
        'name' => 'Spanakopita',
        'image' => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80https://sweetsimplevegan.com/wp-content/uploads/2024/04/vegan_spanakopita_recipe_sweetsimplevegan_6-1025x1536.jpg',
        'description' => 'Greek spinach and feta pie in flaky pastry.',
        'cuisine_type' => 'Greek',
        'meal_type' => 'Snack, Appetizer',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'Athens',
        'city' => 'Athens',
    ],
    [
        'name' => 'Sausage Roll',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.Zlf5ZMZLjnDdQlSDALFatQHaF4?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'British snack of sausage meat wrapped in puff pastry.',
        'cuisine_type' => 'British',
        'meal_type' => 'Snack',
        'dietary_preference' => 'Non-Vegetarian',
        'spice_level' => 'Mild',
        'price_range' => '$$',
        'cooking_style' => 'Baked',
        'state' => 'London',
        'city' => 'London',
    ],
    [
        'name' => 'Churros',
        'image' => 'https://tse1.mm.bing.net/th/id/OIP.zCMZGYpmjxMCkRpmMc5DPwHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        'description' => 'Spanish fried-dough pastry, often dusted with sugar and served with chocolate.',
        'cuisine_type' => 'Spanish',
        'meal_type' => 'Snack, Dessert',
        'dietary_preference' => 'Vegetarian',
        'spice_level' => 'None',
        'price_range' => '$',
        'cooking_style' => 'Fried',
        'state' => 'Madrid',
        'city' => 'Madrid',
    ],
]; 